//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckyWheelWebCore.Source {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuckyWheelWebCore.Source.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຊື້ຮອບໝູນ.
        /// </summary>
        public static string BuyTurn {
            get {
                return ResourceManager.GetString("BuyTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ການຊື້ຮອບໝູນສຳເລັດ, ສືບຕໍ່ການໝຸນໄດ້ເລີຍ!.
        /// </summary>
        public static string BuyTurnSuccess {
            get {
                return ResourceManager.GetString("BuyTurnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ປິດ.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຢືນຢັນ.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຢືນຢັນສຳເລັດ .
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຂໍສະເເດງຄວາມຍິນດີ.
        /// </summary>
        public static string Congratulation {
            get {
                return ResourceManager.GetString("Congratulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ສືບຕໍ່.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຖືກຕ້ອງ.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ກີບ.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ກະລຸນາປ້ອນລະຫັດ OTP ທີ່ທ່ານໄດ້ຮັບໃນຂໍ້ຄວາມເພື່ອສືບຕໍ່.
        /// </summary>
        public static string EnterOtp {
            get {
                return ResourceManager.GetString("EnterOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ກະລຸນາຕື່ມຂໍ້ມູນໃສ່ໃນຟອມນີ້.
        /// </summary>
        public static string FillForm {
            get {
                return ResourceManager.GetString("FillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຊື່ເຕັມ.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ລາກ່ອນ.
        /// </summary>
        public static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ໂຊກດີຄັ້ງຕໍ່ໄປ!.
        /// </summary>
        public static string GoodLuck {
            get {
                return ResourceManager.GetString("GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ກົດລະບຽບຂອງເກມ.
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ລະບຽບຂອງເກມ I-lucky ຢູ່ເທິງ LaoApp&lt;br /&gt;ຮ່ວມຫຼິ້ນເກມnໝູນວົງລໍ້ I-luckyທີ່ LaoApp, ລຸ້ນຮັບເງິນໂປໂມຊັ່ນ, ດາຕ້າອິນເຕີເນັດຟຣີ ແລະ ບັນດາຂອງລາງວັນອື່ນໆຢ່າງຫຼວງຫຼາຍ.&lt;br /&gt;ເວລາໃນການເປີດໃຊ້ງານ:&lt;br /&gt;- ສາມາດຫຼິ້ນໄດ້ທຸກມື້ ເເລະ ທຸກເວລາ&lt;br /&gt;ກຸ່ມເປົ້າໝາຍເຂົ້າຮ່ວມ:&lt;br /&gt;- ລູກຄ້າທັງໝົດທີ່ໄດ້ຕິດຕັ້ງ ແລະ ນຳໃຊ້ LaoApp ຢູ່ໃນລາວ.&lt;br /&gt;ເນື້ອໃນຂອງລາຍການ:&lt;br /&gt;- ກົດເຂົ້າໄປທີ່ LaoApp, ເມື່ອເຂົ້າໄປທີ່ໜ້າຫຼັກ ເເລະ ກົດເຂົ້າໄປທີ່ Icon ຂອງເກມໝຸນວົງລໍ້ I-Lucky ກໍສາມາດໝູນວົງລໍ້ເພື່ອລຸ້ນຂອງລາງວັນໄດ້ທັນທີ.&lt;br /&gt;- ຖ້າວົງລໍ້ຢຸດຢູ່ທີ່ຊ່ອງ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GuideDetail {
            get {
                return ResourceManager.GetString("GuideDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ເຊີນຊວນ.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຕິດຕັ້ງ LaoApp ເພື່ອຮັບດາຕ້າ 500 MB ແລະ 25 ນາທີໂທພາຍໃນເຄືອຂ່າຍ ຫຼື ເບິ່ງວິດິໂອແບບບໍ່ຈຳກັດຟຣີ 30ມື້ໃນ Uclip ຕິດຕັ້ງໄດ້ທີ່ https://bit.ly/301Fo3k ເພື່ອສົ່ງຂໍ້ຄວາມຟຣີ, ໂທວິດິໂອແບບບໍ່ອັ້ນ, ຟັງເພງຟຣີແບບບໍ່ເສຍດາຕ້າ… ແລະ ຍັງມີເກມເພື່ອໃຫ້ທ່ານໄດ້ຫລິ້ນລຸ້ນຮັບຂອງລາງວັນມູນຄ່າ 1.000.000 ກີບໃນທຸກໆມື້ ແລະ 10.000.000 ກີບໃນທ້າຍອາທິດ. LaoApp ຊຸບເປີແອັບທີ່ກຳລັງເປັນທີ່ຍອດນິຍົມທີ່ສຸດໃນລາວກັບຍອດຜູ້ຕິດຕັ້ງນຳໃຊ້ຫຼາຍກວ່າ 1,5 ລ້ານຄົນ..
        /// </summary>
        public static string InviteContent {
            get {
                return ResourceManager.GetString("InviteContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ເຊີນໝູ່ຕິດຕັ້ງ LaoApp.
        /// </summary>
        public static string InviteFriend {
            get {
                return ResourceManager.GetString("InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ເຊີນຊວນໝູ່ຂອງທ່ານຕິດຕັ້ງ LaoApp ເພື່ອສືບຕໍ່.
        /// </summary>
        public static string InviteFriendDetail {
            get {
                return ResourceManager.GetString("InviteFriendDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ເຂົ້າສູ່ລະບົບ.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ກະລຸນາເຂົ້າສູ່ລະບົບກ່ອນ.
        /// </summary>
        public static string LoginFirst {
            get {
                return ResourceManager.GetString("LoginFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ເປີດລິ້ງ.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ໄປທີ່ລິ້ງເພື່ອສືບຕໍ່ໝຸນ.
        /// </summary>
        public static string MissionDetail {
            get {
                return ResourceManager.GetString("MissionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຕໍ່ໄປ.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ບໍ່ມີລາງວັນເເລ້ວ.
        /// </summary>
        public static string NoMorePrize {
            get {
                return ResourceManager.GetString("NoMorePrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ໂອອອອ!.
        /// </summary>
        public static string NotSupport {
            get {
                return ResourceManager.GetString("NotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ທ່ານບໍ່ໄດ້ນຳໃຊ້ເຄືອຂ່າຍຂອງ Unitel. ທ່ານສາມາດກັບຄືນໄປທີ່ Mocha ເພື່ອນຳໃຊ້ບໍລິການອື່ນ. ຂໍຂອບໃຈ.
        /// </summary>
        public static string NotSupportDetail {
            get {
                return ResourceManager.GetString("NotSupportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຮັບ OTP ອີກຄັ້ງໜຶ່ງ.
        /// </summary>
        public static string OtpAgain {
            get {
                return ResourceManager.GetString("OtpAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ລະຫັດ OTP ມີບັນຫາຫຼືບໍ່?.
        /// </summary>
        public static string OtpProblem {
            get {
                return ResourceManager.GetString("OtpProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ອອກຈາກການໝຸນ.
        /// </summary>
        public static string OutOfTurn {
            get {
                return ResourceManager.GetString("OutOfTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຮອບໜຸນຂອງທ່ານໝົດເເລ້ວ, ຊື້ເພື່ອໝຸນຕໍ່. 200ກີບ/ຮອບໝຸນ.
        /// </summary>
        public static string OutOfTurnDetail {
            get {
                return ResourceManager.GetString("OutOfTurnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ລະຫັດຜ່ານ.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ເບີໂທລະສັບ.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ລາງວັນ.
        /// </summary>
        public static string PrizeName {
            get {
                return ResourceManager.GetString("PrizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ເວລາ.
        /// </summary>
        public static string PrizeTime {
            get {
                return ResourceManager.GetString("PrizeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຄຳຖາມ.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຮອບໝຸນ.
        /// </summary>
        public static string RemainSpin {
            get {
                return ResourceManager.GetString("RemainSpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ເເບ່ງປັນ.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ແບ່ງປັນ.
        /// </summary>
        public static string ShareFacebook {
            get {
                return ResourceManager.GetString("ShareFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຫ້ອງລໍຖ້າ.
        /// </summary>
        public static string Showroom {
            get {
                return ResourceManager.GetString("Showroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ໝຸນ.
        /// </summary>
        public static string Spin {
            get {
                return ResourceManager.GetString("Spin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ໝຸນເພື່ອຮັບລາງວັນໃຫຍ່.
        /// </summary>
        public static string SpinSlogan {
            get {
                return ResourceManager.GetString("SpinSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ເວລາໝົດ.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Ads.
        /// </summary>
        public static string ViewAds {
            get {
                return ResourceManager.GetString("ViewAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ສືບຕໍ່.
        /// </summary>
        public static string VisitLink {
            get {
                return ResourceManager.GetString("VisitLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ລໍຖ້າ.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຍິນດີຕ້ອນຮັບ.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ຜິດ.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ລາງວັນຂອງທ່ານ.
        /// </summary>
        public static string YourPrize {
            get {
                return ResourceManager.GetString("YourPrize", resourceCulture);
            }
        }
    }
}
